

CREATE TABLE IF NOT EXISTS DISBURSEMENTS   (
    ID   INTEGER      NOT NULL AUTO_INCREMENT,        
    CLIP_USER VARCHAR(50) DEFAULT '',
    DATE TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	TOTALAMMOUNT DECIMAL(20,2) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS TRANSACTIONS  (
    ID   INTEGER      NOT NULL AUTO_INCREMENT,
    AMOUNT DECIMAL(20,2) NOT NULL,
    CARD_DATA VARCHAR(16) DEFAULT '',
    CLIP_USER VARCHAR(50) DEFAULT '',
    DATE TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
    PAID BOOLEAN,
    ID_DISBURSEMENT  INTEGER DEFAULT null,
    PRIMARY KEY (ID)
);




